---
- name: configure lamp
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/default.yml
  roles:
    - apache
    - mariadb
                                                                                                                                                     
                